### PR TITLE
Support JDK 9 on Alpine

### PR DESCRIPTION
**Pull request by weshouman**

### CODE REVIEW

**Comment by davidcl** [comment]
Thanks for your PR however this repo is a read only duplica of [gitlab.com/scilab/scilab](https://gitlab.com/scilab/scilab). Could you please push your modification there ?

Thanks

**Comment by weshouman** [comment]
I sent the PR twice into the gitlab repo, but in both times I got immediate rejections

**Comment by davidcl** [comment]
In the past both [gitlab ](https://gitlab.com/scilab/scilab)and [github](https://github.com/scilab/scilab) were not used for development purposes in favor of [https://codereview.scilab.org](https://codereview.scilab.org).  This is not the case anymore as **we migrated to [gitlab](https://gitlab.com/scilab/scilab)** in the past few month ; your MR will be accepted there.

**Comment by ycollet** [comment]
Maybe you can put a news on the scilab.org website.
I missed this move :)

**Comment by davidcl** [comment]
👋 @ycollet ; this is still in progress but at least we have a completed gitlab.com/scilab/scilab project (with migrated issues, merge requests, CI/CD pipeline, releases). For branding purposes, we first need to move the existing website before making it official :).

**Comment by ycollet** [comment]
OK ! Perfect for me :)

**Pull request closed without merging**
